import { LevelConfig, WaveConfig } from '../types/index';

const waves: WaveConfig[] = [
  {
    time: 1,
    enemyType: 'diagonal',
    count: 7,
    formation: 'v-shape',
    spawnY: 300,
    spacing: 50,
    hp: 4,
    speed: 180,
    shootInterval: 900,
  },
  {
    time: 4,
    enemyType: 'follow',
    count: 4,
    formation: 'stream',
    spawnY: 100,
    spacing: 90,
    hp: 5,
    speed: 130,
    shootInterval: 700,
  },
  {
    time: 8,
    enemyType: 'sine',
    count: 8,
    formation: 'cluster',
    spawnY: 350,
    spacing: 40,
    hp: 4,
    speed: 170,
    shootInterval: 700,
  },
  {
    time: 12,
    enemyType: 'basic',
    count: 12,
    formation: 'stream',
    spawnY: 200,
    spacing: 30,
    hp: 3,
    speed: 210,
    shootInterval: 600,
  },
  {
    time: 16,
    enemyType: 'follow',
    count: 5,
    formation: 'v-shape',
    spawnY: 300,
    spacing: 60,
    hp: 6,
    speed: 120,
    shootInterval: 500,
  },
  {
    time: 20,
    enemyType: 'diagonal',
    count: 6,
    formation: 'cluster',
    spawnY: 150,
    spacing: 55,
    hp: 5,
    speed: 190,
    shootInterval: 500,
  },
  {
    time: 23,
    enemyType: 'sine',
    count: 5,
    formation: 'line',
    spawnY: 450,
    spacing: 50,
    hp: 5,
    speed: 160,
    shootInterval: 450,
  },
];

export const level6: LevelConfig = {
  name: 'SECTOR 6 - VOID PASSAGE',
  waves,
  bossTime: 30,
  scrollSpeed: 1.7,
  backgroundColor: 0x0a000a,
};
