import { LevelConfig, WaveConfig } from '../types/index';

const waves: WaveConfig[] = [
  {
    time: 1,
    enemyType: 'sine',
    count: 8,
    formation: 'cluster',
    spawnY: 200,
    spacing: 40,
    hp: 5,
    speed: 190,
    shootInterval: 600,
  },
  {
    time: 4,
    enemyType: 'follow',
    count: 5,
    formation: 'v-shape',
    spawnY: 400,
    spacing: 60,
    hp: 6,
    speed: 140,
    shootInterval: 500,
  },
  {
    time: 8,
    enemyType: 'diagonal',
    count: 8,
    formation: 'line',
    spawnY: 150,
    spacing: 50,
    hp: 5,
    speed: 210,
    shootInterval: 500,
  },
  {
    time: 12,
    enemyType: 'basic',
    count: 14,
    formation: 'stream',
    spawnY: 300,
    spacing: 25,
    hp: 4,
    speed: 230,
    shootInterval: 450,
  },
  {
    time: 16,
    enemyType: 'follow',
    count: 6,
    formation: 'cluster',
    spawnY: 250,
    spacing: 65,
    hp: 7,
    speed: 140,
    shootInterval: 400,
  },
  {
    time: 20,
    enemyType: 'sine',
    count: 7,
    formation: 'v-shape',
    spawnY: 350,
    spacing: 45,
    hp: 6,
    speed: 180,
    shootInterval: 400,
  },
  {
    time: 24,
    enemyType: 'diagonal',
    count: 6,
    formation: 'cluster',
    spawnY: 100,
    spacing: 55,
    hp: 6,
    speed: 200,
    shootInterval: 350,
  },
];

export const level8: LevelConfig = {
  name: 'SECTOR 8 - BINARY STAR',
  waves,
  bossTime: 32,
  scrollSpeed: 1.9,
  backgroundColor: 0x0a0500,
};
