import { LevelConfig, WaveConfig } from '../types/index';

const waves: WaveConfig[] = [
  {
    time: 1,
    enemyType: 'follow',
    count: 6,
    formation: 'v-shape',
    spawnY: 300,
    spacing: 60,
    hp: 6,
    speed: 150,
    shootInterval: 500,
  },
  {
    time: 4,
    enemyType: 'diagonal',
    count: 8,
    formation: 'cluster',
    spawnY: 150,
    spacing: 45,
    hp: 6,
    speed: 210,
    shootInterval: 450,
  },
  {
    time: 8,
    enemyType: 'sine',
    count: 9,
    formation: 'stream',
    spawnY: 400,
    spacing: 40,
    hp: 5,
    speed: 200,
    shootInterval: 450,
  },
  {
    time: 12,
    enemyType: 'basic',
    count: 14,
    formation: 'v-shape',
    spawnY: 250,
    spacing: 35,
    hp: 5,
    speed: 240,
    shootInterval: 400,
  },
  {
    time: 16,
    enemyType: 'follow',
    count: 7,
    formation: 'stream',
    spawnY: 200,
    spacing: 80,
    hp: 7,
    speed: 150,
    shootInterval: 350,
  },
  {
    time: 20,
    enemyType: 'diagonal',
    count: 8,
    formation: 'line',
    spawnY: 350,
    spacing: 50,
    hp: 6,
    speed: 220,
    shootInterval: 350,
  },
  {
    time: 24,
    enemyType: 'sine',
    count: 7,
    formation: 'cluster',
    spawnY: 100,
    spacing: 45,
    hp: 7,
    speed: 190,
    shootInterval: 300,
  },
  {
    time: 27,
    enemyType: 'follow',
    count: 4,
    formation: 'line',
    spawnY: 450,
    spacing: 100,
    hp: 8,
    speed: 140,
    shootInterval: 300,
  },
];

export const level9: LevelConfig = {
  name: 'SECTOR 9 - DARK MATTER',
  waves,
  bossTime: 35,
  scrollSpeed: 2.0,
  backgroundColor: 0x050005,
};
