import { LevelConfig, WaveConfig } from '../types/index';

const waves: WaveConfig[] = [
  {
    time: 1,
    enemyType: 'diagonal',
    count: 6,
    formation: 'stream',
    spawnY: 100,
    spacing: 50,
    hp: 3,
    speed: 170,
    shootInterval: 1200,
  },
  {
    time: 4,
    enemyType: 'follow',
    count: 3,
    formation: 'line',
    spawnY: 400,
    spacing: 80,
    hp: 4,
    speed: 100,
    shootInterval: 900,
  },
  {
    time: 8,
    enemyType: 'sine',
    count: 7,
    formation: 'v-shape',
    spawnY: 300,
    spacing: 45,
    hp: 3,
    speed: 150,
    shootInterval: 1000,
  },
  {
    time: 12,
    enemyType: 'basic',
    count: 10,
    formation: 'cluster',
    spawnY: 250,
    spacing: 35,
    hp: 2,
    speed: 190,
    shootInterval: 800,
  },
  {
    time: 16,
    enemyType: 'diagonal',
    count: 5,
    formation: 'v-shape',
    spawnY: 200,
    spacing: 60,
    hp: 4,
    speed: 160,
    shootInterval: 700,
  },
  {
    time: 20,
    enemyType: 'follow',
    count: 5,
    formation: 'cluster',
    spawnY: 350,
    spacing: 70,
    hp: 5,
    speed: 110,
    shootInterval: 600,
  },
];

export const level4: LevelConfig = {
  name: 'SECTOR 4 - COSMIC DRIFT',
  waves,
  bossTime: 28,
  scrollSpeed: 1.5,
  backgroundColor: 0x050011,
};
