import { LevelConfig, WaveConfig } from '../types/index';

const waves: WaveConfig[] = [
  {
    time: 1,
    enemyType: 'follow',
    count: 6,
    formation: 'cluster',
    spawnY: 250,
    spacing: 60,
    hp: 7,
    speed: 160,
    shootInterval: 400,
  },
  {
    time: 4,
    enemyType: 'diagonal',
    count: 10,
    formation: 'v-shape',
    spawnY: 300,
    spacing: 45,
    hp: 6,
    speed: 230,
    shootInterval: 400,
  },
  {
    time: 8,
    enemyType: 'sine',
    count: 10,
    formation: 'stream',
    spawnY: 150,
    spacing: 35,
    hp: 6,
    speed: 210,
    shootInterval: 350,
  },
  {
    time: 12,
    enemyType: 'basic',
    count: 16,
    formation: 'cluster',
    spawnY: 350,
    spacing: 30,
    hp: 5,
    speed: 250,
    shootInterval: 350,
  },
  {
    time: 16,
    enemyType: 'follow',
    count: 8,
    formation: 'v-shape',
    spawnY: 200,
    spacing: 70,
    hp: 8,
    speed: 160,
    shootInterval: 300,
  },
  {
    time: 20,
    enemyType: 'diagonal',
    count: 8,
    formation: 'cluster',
    spawnY: 400,
    spacing: 50,
    hp: 7,
    speed: 230,
    shootInterval: 300,
  },
  {
    time: 24,
    enemyType: 'sine',
    count: 8,
    formation: 'line',
    spawnY: 100,
    spacing: 45,
    hp: 7,
    speed: 200,
    shootInterval: 250,
  },
  {
    time: 27,
    enemyType: 'follow',
    count: 6,
    formation: 'stream',
    spawnY: 450,
    spacing: 80,
    hp: 9,
    speed: 150,
    shootInterval: 250,
  },
  {
    time: 30,
    enemyType: 'diagonal',
    count: 6,
    formation: 'v-shape',
    spawnY: 300,
    spacing: 55,
    hp: 8,
    speed: 220,
    shootInterval: 200,
  },
];

export const level10: LevelConfig = {
  name: 'SECTOR 10 - SUPERNOVA',
  waves,
  bossTime: 38,
  scrollSpeed: 2.2,
  backgroundColor: 0x0a0000,
};
