import { LevelConfig, WaveConfig } from '../types/index';

const waves: WaveConfig[] = [
  {
    time: 1,
    enemyType: 'follow',
    count: 4,
    formation: 'stream',
    spawnY: 300,
    spacing: 100,
    hp: 4,
    speed: 120,
    shootInterval: 800,
  },
  {
    time: 4,
    enemyType: 'sine',
    count: 8,
    formation: 'line',
    spawnY: 150,
    spacing: 40,
    hp: 3,
    speed: 170,
    shootInterval: 1000,
  },
  {
    time: 8,
    enemyType: 'diagonal',
    count: 6,
    formation: 'cluster',
    spawnY: 400,
    spacing: 50,
    hp: 4,
    speed: 180,
    shootInterval: 800,
  },
  {
    time: 11,
    enemyType: 'basic',
    count: 10,
    formation: 'v-shape',
    spawnY: 300,
    spacing: 45,
    hp: 3,
    speed: 200,
    shootInterval: 700,
  },
  {
    time: 15,
    enemyType: 'follow',
    count: 5,
    formation: 'cluster',
    spawnY: 200,
    spacing: 60,
    hp: 5,
    speed: 130,
    shootInterval: 600,
  },
  {
    time: 19,
    enemyType: 'sine',
    count: 6,
    formation: 'stream',
    spawnY: 250,
    spacing: 55,
    hp: 4,
    speed: 160,
    shootInterval: 600,
  },
  {
    time: 22,
    enemyType: 'diagonal',
    count: 4,
    formation: 'line',
    spawnY: 450,
    spacing: 70,
    hp: 5,
    speed: 170,
    shootInterval: 500,
  },
];

export const level5: LevelConfig = {
  name: 'SECTOR 5 - PLASMA FIELDS',
  waves,
  bossTime: 30,
  scrollSpeed: 1.6,
  backgroundColor: 0x0a0a00,
};
