import { LevelConfig, WaveConfig } from '../types/index';

const waves: WaveConfig[] = [
  {
    time: 1,
    enemyType: 'sine',
    count: 6,
    formation: 'stream',
    spawnY: 200,
    spacing: 45,
    hp: 2,
    speed: 160,
    shootInterval: 1400,
  },
  {
    time: 4,
    enemyType: 'diagonal',
    count: 5,
    formation: 'v-shape',
    spawnY: 350,
    spacing: 55,
    hp: 2,
    speed: 170,
    shootInterval: 1200,
  },
  {
    time: 8,
    enemyType: 'follow',
    count: 4,
    formation: 'cluster',
    spawnY: 150,
    spacing: 60,
    hp: 3,
    speed: 110,
    shootInterval: 1000,
  },
  {
    time: 12,
    enemyType: 'basic',
    count: 8,
    formation: 'line',
    spawnY: 450,
    spacing: 40,
    hp: 2,
    speed: 180,
    shootInterval: 900,
  },
  {
    time: 16,
    enemyType: 'sine',
    count: 6,
    formation: 'cluster',
    spawnY: 300,
    spacing: 50,
    hp: 3,
    speed: 150,
    shootInterval: 800,
  },
  {
    time: 20,
    enemyType: 'follow',
    count: 4,
    formation: 'stream',
    spawnY: 100,
    spacing: 120,
    hp: 4,
    speed: 120,
    shootInterval: 700,
  },
];

export const level3: LevelConfig = {
  name: 'SECTOR 3 - ION STORM',
  waves,
  bossTime: 28,
  scrollSpeed: 1.4,
  backgroundColor: 0x001111,
};
