import { LevelConfig, WaveConfig } from '../types/index';

const waves: WaveConfig[] = [
  {
    time: 1,
    enemyType: 'follow',
    count: 5,
    formation: 'cluster',
    spawnY: 250,
    spacing: 70,
    hp: 5,
    speed: 140,
    shootInterval: 700,
  },
  {
    time: 4,
    enemyType: 'diagonal',
    count: 8,
    formation: 'stream',
    spawnY: 100,
    spacing: 45,
    hp: 4,
    speed: 200,
    shootInterval: 600,
  },
  {
    time: 8,
    enemyType: 'sine',
    count: 7,
    formation: 'v-shape',
    spawnY: 400,
    spacing: 50,
    hp: 5,
    speed: 180,
    shootInterval: 600,
  },
  {
    time: 12,
    enemyType: 'basic',
    count: 12,
    formation: 'cluster',
    spawnY: 300,
    spacing: 35,
    hp: 4,
    speed: 220,
    shootInterval: 500,
  },
  {
    time: 16,
    enemyType: 'follow',
    count: 6,
    formation: 'line',
    spawnY: 200,
    spacing: 80,
    hp: 6,
    speed: 130,
    shootInterval: 500,
  },
  {
    time: 20,
    enemyType: 'diagonal',
    count: 7,
    formation: 'v-shape',
    spawnY: 350,
    spacing: 55,
    hp: 5,
    speed: 190,
    shootInterval: 400,
  },
  {
    time: 24,
    enemyType: 'sine',
    count: 6,
    formation: 'stream',
    spawnY: 150,
    spacing: 50,
    hp: 6,
    speed: 170,
    shootInterval: 400,
  },
];

export const level7: LevelConfig = {
  name: 'SECTOR 7 - CHROME HORIZON',
  waves,
  bossTime: 32,
  scrollSpeed: 1.8,
  backgroundColor: 0x000a0a,
};
